platform :ios, '7.0'
pod 'FMDB'
pod 'SSZipArchive'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'PureLayout'
pod 'IQKeyboardManager'
pod 'Reachability'

#pod 'SDCycleScrollView'  #图片轮播器